[site]
cname = "laddge.net"  # for GitHub Pages
lang = "ja"
title = "Laddgeのプロフィール"
meta_desc = "Laddgeは高校生"
icon = "img/profile.png"

[ogp]
title = "Laddgeのプロフィール"
desc = "Laddgeは高校生"
url = "https://laddge.net/"
image = "https://github.com/laddge.png"
twitter = "@laddge_"

[main]
name = "Laddge"
desc = "趣味でプログラミングなどをしてる高校3年生のLaddge(らっじ)です。<br>Linuxが大好きです。友達の影響でvimmerです。<br>プログラミング好きな人が集う場所として、Discord上に「<a href=\"https://shebang.laddge.net\" target=\"_blank\">Shebang</a>」というコミュニティを作って運営しています。気軽に参加してみてください。"
profile_image = "img/profile.png"
devicons = ["python", "linux", "vim", "javascript", "bash", "c"]

[social]
github = "https://github.com/laddge"
twitter = "https://twitter.com/laddge_"
instagram = "https://instagram.com/laddge_"
line = "https://line.laddge.net/"
